### PR TITLE
In-Development

### PR DESCRIPTION
**Pull request by ShyamSS-95**
To be added:
- Poisson solvers haven't been added back in as of yet. The code still uses an analytical expression for the fields.
- FDTD bug fix.

### CODE REVIEW

**Comment by ShyamSS-95** [comment]
- The gradient function cannot be simplified to:
`df_dv_x, df_dv_y, df_dv_z = np.gradient(f_background_local, dv_x, dv_y, dv_z)`
There is a reason why the function has been written in the current fashion. 
`np.gradient` throws errors when only one element is contained along a particular axis. To overcome this the values are assigned based on the condition.

- Please tell the commit tag that you are using. As far as I remember, the `Sage worksheet` link has been provided under function documentation. What is the documentation which has been provided for you?

**Comment by mchandra** [comment]
- Ok, the slicing is fine then. Document why it has been written in that way inside the code
- What about passing `dv_x` etc as params into `np.gradient` instead of dividing by it? Is this a bug?
- Oops yes, I see that you put a shortened link in the documentation.

**Comment by ShyamSS-95** [comment]
- I don't think it's a bug. I've had it changed nevertheless. I compared the solution given by the method I had used and the method you had suggested. This is what I got:
```python
# dfdvy1 is the method you suggested
# dfdvy2 is the method I'd used
In [14]: np.sum(dfdvy1-dfdvy2)
Out[14]: -1.3600294294607247e-15
```

**Comment by mchandra** [comment]
You should check `np.sum(np.abs(dfdvy1 - dfdvy2))`

**Comment by ShyamSS-95** [comment]
I'd made a mistake earlier.
```python
In [42]: np.sum(abs(dfdvy1-dfdvy2))
Out[42]: 0.0

In [43]: np.sum((dfdvy1-dfdvy2))
Out[43]: 0.0
```

**Comment by mchandra** [comment]
- Rename `lts` to `linear_solver` and `cks` to `non_linear_solver`

## Non-linear solver
- Use `petscprinf()` to print instead of using `if (comm.rank==0) ...`

### Code structure 
Lets discuss the overall structure before getting into implementation details:

- There appears to be a large amount of code duplication between all `run_ck.py` files for different physics problems. Can most of it be moved to a higher level data structure that has `da` as an internal variable which it initializes during instantiation, along with auxiliary variables such as `i_left`, `j_bottom` `x_center` etc. ?
-

**Comment by ShyamSS-95** [comment]
Instead of moving the code in `run_non_linear_solver.py` and `run_linear_solver.py` to a higher level data structure, what do you think of having a symbolic link like `non_linear_solver` and `linear_solver` to the appropriate python files, which will take an argument as `params.py`. We'll set this up using `argparse`. Then running the files would require something like:
```bash
non_linear_solver run params.py
linear_solver run params.py
```

**Comment by mchandra** [comment]
What we'd like is a *library* whose components can be used without the user having to code internal details like initializing `da, vec` objects in the main script. In the current approach, it makes it awkward to do so because all the specifics of the algorithm such as `x_center` etc are in the main script. To do anything beyond a run, say post-processing in parallel, would require lots of code copy-paste leading to errors. 

How about something like:
```
class physical_system:
  time
  dump(variables, filename_append)
  compute_moments(moment) # moment is any function of (v1, v2, v3)

  __init__(domain, boundaries, initial_conditions)
  # boundaries(x1, x2), initial_conditions(x1, x2, v1, v2, v3)
  # ... and various system variables such as rho, P and parameters such as tau, the collision time scale

  __init__(filename) # load from a dump
  
class linear_solver:
  # Contains all internal details of the algorithm and parallelization such as da, globalVec, localVec etc
  __init__(physical_system, background, N_x1, N_x2, N_v1, N_v2, N_v3)

 compute_initial_perturbation()
 # perform a spatial FFT of (system.initial_conditions - background)

 evolve(t)

class nonlinear_solver:
  __init__(physical_system, N_x1, N_x2, N_v1, N_v2, N_v3)

  evolve(t)
```

The library is then used to write a `main.py`:
```
import params
import physical_system, linear_solver, nonlinear_solver

system_1D_1V = physical_system(domain, boundaries, initial_conditions)

N_x2 = params.N_x2
N_v1 = params.N_v1
N_v2 = params.N_v2
N_v3 = params.N_v3
for N_x1 in np.array([32, 64, 128, 256, 512]):
  system_linear_evolution    = linear_solver(system_1D_1V, background, N_x1, N_x2, N_v1, N_v2, N_v3).evolve(t)
  system_nonlinear_evolution = nonlinear_solver(system_1D_1V, N_x1, N_x2, N_v1, N_v2, N_v3).evolve(t)
  err_rho.append(sum(abs(system_linear_evolution.rho - system_nonlinear_evolution.rho))
  
  system_linear_evolution.dump(rho, P, q, filename_append='_N_' + str(N_x1)) # dump only important variables
  system_linear_evolution.dump( filename_append='_N_' + str(N_x1)) # dump the full state of the system
```

After the simulation is complete, say we want to compute something interesting:
```
import params
import physical_system
import nonlinear_solver
import matplotlib.pyplot as plt

system_1D_1V = physical_system('system_state_time_index_532_N_32.h5')

heat_flux = system_1D_1V.compute_moments(v1**3)
plt.plot(x1, heat_flux)

# Now I also want to evolve the system for a little longer
system_linear_evolution = linear_solver(system_1D_1V, background, N_x1, 2, 32, 32, 32).evolve(t)
```

**Pull request merged**
